# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: XJDHDR
open_collective: # Replace with a single Open Collective username
ko_fi: XJDHDR
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: XJDHDR
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: https://www.paypal.com/donate/?token=ykdukjiWkqz3LGOSvOu-miw3vlp4-KbIh6MKcjMKsam7XLPkcnA3HBpQACYOP-tKRkaCni33FudPMHy2&Z3JncnB0=
